# Generated by Django 4.2.1 on 2023-06-22 01:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serie', models.CharField(blank=True, max_length=200)),
                ('creacion', models.DateTimeField()),
                ('modificacion', models.DateTimeField()),
            ],
            options={
                'db_table': 'api_medio',
            },
        ),
        migrations.CreateModel(
            name='TipoComponente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='TipoDepartamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='TipoDivision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='TipoEstadoMedio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='TipoEstadoSello',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='TipoMarca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='TipoMedio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=100)),
                ('slug', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='TipoMunicipio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='TipoPeriferico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='TipoPiso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='TipopPrograma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='TipoProvincia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TipoRam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='TipoSistemaOperativo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='TipoUnidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=200)),
                ('division', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api_app.tipodivision')),
                ('municipio', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api_app.tipomunicipio')),
            ],
        ),
        migrations.CreateModel(
            name='Componente',
            fields=[
                ('medio_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api_app.medio')),
                ('tipo_capacidad', models.CharField(max_length=200)),
                ('tipo_frecuencia', models.CharField(max_length=200)),
                ('tipo_componente', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='api_app.tipocomponente')),
            ],
            bases=('api_app.medio',),
        ),
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('medio_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api_app.medio')),
                ('inventario', models.CharField(max_length=200)),
            ],
            bases=('api_app.medio',),
        ),
        migrations.CreateModel(
            name='Ubicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departamento', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api_app.tipodepartamento')),
                ('division', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api_app.tipodivision')),
                ('municipio', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api_app.tipomunicipio')),
                ('piso', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api_app.tipopiso')),
                ('unidad', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api_app.tipounidad')),
            ],
        ),
        migrations.AddField(
            model_name='tipopiso',
            name='division',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api_app.tipounidad'),
        ),
        migrations.AddField(
            model_name='tipomunicipio',
            name='provincia',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api_app.tipoprovincia'),
        ),
        migrations.CreateModel(
            name='TipoModelo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=200)),
                ('marca', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api_app.tipomarca')),
            ],
        ),
        migrations.AddField(
            model_name='tipodivision',
            name='provincia',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api_app.tipoprovincia'),
        ),
        migrations.AddField(
            model_name='tipodepartamento',
            name='division',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api_app.tipodivision'),
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('noMediore', models.CharField(max_length=200)),
                ('ubicacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_app.ubicacion')),
            ],
        ),
        migrations.AddField(
            model_name='medio',
            name='estado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_app.tipoestadomedio'),
        ),
        migrations.AddField(
            model_name='medio',
            name='marca',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_app.tipomarca'),
        ),
        migrations.AddField(
            model_name='medio',
            name='modelo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_app.tipomodelo'),
        ),
        migrations.AddField(
            model_name='medio',
            name='responsable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_app.persona'),
        ),
        migrations.AddField(
            model_name='medio',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_app.tipomedio'),
        ),
        migrations.AddField(
            model_name='medio',
            name='ubicacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_app.ubicacion'),
        ),
        migrations.CreateModel(
            name='Periferico',
            fields=[
                ('medio_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api_app.medio')),
                ('conectado_a', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tags', related_query_name='tag', to='api_app.medio', verbose_name='conexion')),
                ('tipo_periferico', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='api_app.tipoperiferico')),
            ],
            options={
                'db_table': 'api_periferico',
            },
            bases=('api_app.medio',),
        ),
        migrations.CreateModel(
            name='Computadora',
            fields=[
                ('medio_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api_app.medio')),
                ('ip', models.CharField(max_length=200)),
                ('servicio', models.CharField(max_length=200)),
                ('usuario', models.CharField(max_length=200)),
                ('mac', models.CharField(max_length=200)),
                ('nombrepc', models.CharField(max_length=200)),
                ('sello', models.CharField(max_length=200)),
                ('componentes', models.ManyToManyField(related_name='componentes', to='api_app.componente')),
                ('estado_sello', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='api_app.tipoestadosello')),
                ('sistema_operativo', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='api_app.tiposistemaoperativo')),
            ],
            bases=('api_app.medio',),
        ),
    ]
