# Generated by Django 4.2.1 on 2023-06-22 02:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='componente',
            name='tipo_ram',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='api_app.tiporam'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='ubicacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api_app.ubicacion'),
        ),
        migrations.AlterField(
            model_name='ubicacion',
            name='departamento',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='api_app.tipodepartamento'),
        ),
        migrations.AlterField(
            model_name='ubicacion',
            name='division',
            field=models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, to='api_app.tipodivision'),
        ),
        migrations.AlterField(
            model_name='ubicacion',
            name='municipio',
            field=models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, to='api_app.tipomunicipio'),
        ),
        migrations.AlterField(
            model_name='ubicacion',
            name='piso',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api_app.tipopiso'),
        ),
        migrations.AlterField(
            model_name='ubicacion',
            name='unidad',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='api_app.tipounidad'),
        ),
    ]
