# Generated by Django 4.2.1 on 2023-06-22 02:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0002_componente_tipo_ram_alter_persona_ubicacion_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='computadora',
            table='api_computadora',
        ),
        migrations.AlterModelTable(
            name='equipo',
            table='api_equipo',
        ),
        migrations.AlterModelTable(
            name='persona',
            table='api_persona',
        ),
        migrations.AlterModelTable(
            name='ubicacion',
            table='api_ubicacion',
        ),
    ]
