# Generated by Django 4.2.1 on 2023-06-22 02:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0003_alter_computadora_table_alter_equipo_table_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='componente',
            table='api_componente',
        ),
    ]
