# Generated by Django 4.2.1 on 2023-06-22 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0005_computadora_es_servidor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='persona',
            old_name='noMediore',
            new_name='nombre',
        ),
    ]
