# Generated by Django 4.2.1 on 2023-06-22 08:06

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0006_rename_nomediore_persona_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medio',
            name='creacion',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 22, 3, 6, 44, 362961)),
        ),
        migrations.AlterField(
            model_name='medio',
            name='estado',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api_app.tipoestadomedio'),
        ),
        migrations.AlterField(
            model_name='medio',
            name='marca',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api_app.tipomarca'),
        ),
        migrations.AlterField(
            model_name='medio',
            name='modelo',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='api_app.tipomodelo'),
        ),
        migrations.AlterField(
            model_name='medio',
            name='modificacion',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 22, 3, 6, 44, 362961)),
        ),
        migrations.AlterField(
            model_name='medio',
            name='responsable',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api_app.persona'),
        ),
        migrations.AlterField(
            model_name='medio',
            name='ubicacion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api_app.ubicacion'),
        ),
    ]
