# Generated by Django 4.2.1 on 2023-06-22 17:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0007_alter_medio_creacion_alter_medio_estado_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tipocomponente',
            options={'verbose_name': 'componente', 'verbose_name_plural': 'componentes'},
        ),
        migrations.AlterModelOptions(
            name='tipodepartamento',
            options={'verbose_name': 'departamento', 'verbose_name_plural': 'departamentos'},
        ),
        migrations.AlterModelOptions(
            name='tipodivision',
            options={'verbose_name': 'division', 'verbose_name_plural': 'divisiones'},
        ),
        migrations.AlterModelOptions(
            name='tipoestadomedio',
            options={'verbose_name': 'estado del medio', 'verbose_name_plural': 'estados de los medios'},
        ),
        migrations.AlterModelOptions(
            name='tipoestadosello',
            options={'verbose_name': 'estado del sello', 'verbose_name_plural': 'estado de los sellos'},
        ),
        migrations.AlterModelOptions(
            name='tipomarca',
            options={'verbose_name': 'marca', 'verbose_name_plural': 'marcas'},
        ),
        migrations.AlterModelOptions(
            name='tipomedio',
            options={'verbose_name': 'tipo de medio', 'verbose_name_plural': 'tipos de medios'},
        ),
        migrations.AlterModelOptions(
            name='tipomodelo',
            options={'verbose_name': 'modelo', 'verbose_name_plural': 'modelos'},
        ),
        migrations.AlterModelOptions(
            name='tipomunicipio',
            options={'verbose_name': 'municipo', 'verbose_name_plural': 'municipos'},
        ),
        migrations.AlterModelOptions(
            name='tipoperiferico',
            options={'verbose_name': 'tipo de periferico', 'verbose_name_plural': 'tipos de perifericos'},
        ),
        migrations.AlterModelOptions(
            name='tipopiso',
            options={'verbose_name': 'no. piso', 'verbose_name_plural': 'no. de pisos'},
        ),
        migrations.AlterModelOptions(
            name='tipopprograma',
            options={'verbose_name': 'programa', 'verbose_name_plural': 'programas'},
        ),
        migrations.AlterModelOptions(
            name='tipoprovincia',
            options={'verbose_name': 'provincia', 'verbose_name_plural': 'provincias'},
        ),
        migrations.AlterModelOptions(
            name='tiporam',
            options={'verbose_name': 'tipo de memoria ram', 'verbose_name_plural': 'tipos de memoria ram'},
        ),
        migrations.AlterModelOptions(
            name='tiposistemaoperativo',
            options={'verbose_name': 'sistema operativo', 'verbose_name_plural': 'sistemas operativos'},
        ),
        migrations.AlterModelOptions(
            name='tipounidad',
            options={'verbose_name': 'unidad', 'verbose_name_plural': 'unidades'},
        ),
        migrations.AlterField(
            model_name='medio',
            name='creacion',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 22, 12, 24, 5, 935520)),
        ),
        migrations.AlterField(
            model_name='medio',
            name='modificacion',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 22, 12, 24, 5, 935520)),
        ),
    ]
