# Generated by Django 4.2.1 on 2023-06-22 17:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0008_alter_tipocomponente_options_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TipopPrograma',
            new_name='TipoPrograma',
        ),
        migrations.AlterField(
            model_name='medio',
            name='creacion',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 22, 12, 25, 21, 222194)),
        ),
        migrations.AlterField(
            model_name='medio',
            name='modificacion',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 22, 12, 25, 21, 222194)),
        ),
    ]
