# Generated by Django 4.2.1 on 2023-06-22 17:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0009_rename_tipopprograma_tipoprograma_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipoperiferico',
            name='slug',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='medio',
            name='creacion',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 22, 12, 59, 41, 60890)),
        ),
        migrations.AlterField(
            model_name='medio',
            name='modificacion',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 22, 12, 59, 41, 60890)),
        ),
        migrations.AlterField(
            model_name='medio',
            name='tipo',
            field=models.CharField(choices=[('EQ', 'Equipo'), ('MD', 'Medio'), ('PER', 'Periferico'), ('PC', 'Computadora'), ('CMP', 'Componente')], default='EQ', max_length=7),
        ),
        migrations.DeleteModel(
            name='TipoMedio',
        ),
    ]
