# Generated by Django 4.2.1 on 2023-06-23 00:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0010_tipoperiferico_slug_alter_medio_creacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medio',
            name='creacion',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 22, 19, 8, 28, 29671)),
        ),
        migrations.AlterField(
            model_name='medio',
            name='modificacion',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 22, 19, 8, 28, 29671)),
        ),
    ]
