# Generated by Django 4.2.1 on 2023-06-29 01:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0011_alter_medio_creacion_alter_medio_modificacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='ubicacion',
            name='text',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='medio',
            name='creacion',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 28, 20, 58, 46, 259532)),
        ),
        migrations.AlterField(
            model_name='medio',
            name='modificacion',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 28, 20, 58, 46, 259532)),
        ),
        migrations.AlterField(
            model_name='medio',
            name='tipo',
            field=models.CharField(choices=[('equipo', 'Equipo'), ('periferico', 'Periferico'), ('computadora', 'Computadora'), ('componente', 'Componente')], default='equipo', max_length=21),
        ),
    ]
