# Generated by Django 4.2.1 on 2023-07-01 23:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0014_alter_medio_creacion_alter_medio_modificacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medio',
            name='creacion',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 1, 18, 1, 45, 1727)),
        ),
        migrations.AlterField(
            model_name='medio',
            name='modificacion',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 1, 18, 1, 45, 1727)),
        ),
        migrations.AddIndex(
            model_name='medio',
            index=models.Index(fields=['tipo'], name='api_medio_tipo_b7e410_idx'),
        ),
        migrations.AddIndex(
            model_name='medio',
            index=models.Index(fields=['marca', 'modelo'], name='api_medio_marca_i_9992c2_idx'),
        ),
    ]
