# Generated by Django 4.2.1 on 2023-07-02 17:40

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0016_remove_medio_api_medio_marca_i_9992c2_idx_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='computadora',
            name='componentes',
        ),
        migrations.AddField(
            model_name='componente',
            name='medio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='api_app.computadora'),
        ),
        migrations.AlterField(
            model_name='medio',
            name='creacion',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 2, 12, 40, 25, 766108)),
        ),
        migrations.AlterField(
            model_name='medio',
            name='modificacion',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 2, 12, 40, 25, 766108)),
        ),
    ]
