# Generated by Django 4.2.1 on 2023-07-02 20:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0017_remove_computadora_componentes_componente_medio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tiposistemaoperativo',
            name='version',
            field=models.CharField(default='10', max_length=20),
        ),
        migrations.AlterField(
            model_name='computadora',
            name='nombrepc',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='computadora',
            name='sello',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='computadora',
            name='servicio',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='computadora',
            name='usuario',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='medio',
            name='creacion',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 2, 15, 14, 32, 682417)),
        ),
        migrations.AlterField(
            model_name='medio',
            name='modificacion',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 2, 15, 14, 32, 682417)),
        ),
    ]
