# Generated by Django 4.2.1 on 2023-07-08 05:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0021_alter_medio_creacion_alter_medio_estado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medio',
            name='creacion',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 8, 0, 30, 22, 357644)),
        ),
        migrations.AlterField(
            model_name='medio',
            name='modificacion',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 8, 5, 30, 22, 357644, tzinfo=datetime.timezone.utc)),
        ),
    ]
