# Generated by Django 4.2.1 on 2023-07-21 04:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0022_alter_medio_creacion_alter_medio_modificacion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tipopiso',
            old_name='division',
            new_name='unidad',
        ),
        migrations.AlterField(
            model_name='medio',
            name='creacion',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 20, 22, 57, 3, 926883)),
        ),
        migrations.AlterField(
            model_name='medio',
            name='modificacion',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 21, 3, 57, 3, 926883, tzinfo=datetime.timezone.utc)),
        ),
    ]
