# Generated by Django 4.2.1 on 2023-07-21 04:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0023_rename_division_tipopiso_unidad_alter_medio_creacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medio',
            name='creacion',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 20, 23, 4, 4, 29896)),
        ),
        migrations.AlterField(
            model_name='medio',
            name='modificacion',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 21, 4, 4, 4, 29896, tzinfo=datetime.timezone.utc)),
        ),
    ]
