# Generated by Django 4.2.1 on 2023-07-21 04:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0027_alter_medio_creacion_alter_medio_modificacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medio',
            name='creacion',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 21, 4, 6, 21, 631788, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='medio',
            name='modificacion',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 21, 4, 6, 21, 631788, tzinfo=datetime.timezone.utc)),
        ),
    ]
