# Generated by Django 4.2.1 on 2023-07-25 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0029_alter_medio_creacion_alter_medio_modificacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computadora',
            name='estado_sello',
            field=models.CharField(choices=[('B', 'Bien'), ('S', 'Sin Sello'), ('R', 'Roto')], default='B', max_length=21),
        ),
        migrations.DeleteModel(
            name='TipoEstadoSello',
        ),
    ]
