# Generated by Django 4.2.1 on 2023-07-25 05:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0030_alter_computadora_estado_sello_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medio',
            name='modelo',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.RESTRICT, to='api_app.tipomodelo'),
        ),
        migrations.AlterField(
            model_name='periferico',
            name='conectado_a',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tags', related_query_name='tag', to='api_app.medio', verbose_name='conexion'),
        ),
    ]
