# Generated by Django 4.2.1 on 2023-07-25 23:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0036_alter_periferico_conectado_a'),
    ]

    operations = [
        migrations.RenameField(
            model_name='componente',
            old_name='tipo_capacidad',
            new_name='capacidad',
        ),
        migrations.RenameField(
            model_name='componente',
            old_name='tipo_frecuencia',
            new_name='frecuencia',
        ),
        migrations.RemoveField(
            model_name='componente',
            name='tipo_ram',
        ),
        migrations.AlterField(
            model_name='componente',
            name='tipo_componente',
            field=models.CharField(choices=[('ram', 'Ram'), ('disco', 'Disco Duro')], default='disco', max_length=21),
        ),
        migrations.AlterField(
            model_name='periferico',
            name='conectado_a',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tags', related_query_name='tag', to='api_app.medio', verbose_name='conexion'),
        ),
        migrations.DeleteModel(
            name='TipoRam',
        ),
    ]
