# Generated by Django 4.2.1 on 2023-07-27 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0037_rename_tipo_capacidad_componente_capacidad_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='componente',
            name='tipo_ram',
            field=models.CharField(choices=[('DDR1', 'Ddr1'), ('DDR2', 'Ddr2'), ('DDR3', 'Ddr3'), ('DDR4', 'Ddr4')], max_length=200, null=True),
        ),
    ]
