# Generated by Django 4.2.1 on 2023-07-28 22:04

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0039_delete_tipocomponente_alter_componente_tipo_ram'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovimientoComponente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serie', models.CharField(max_length=200)),
                ('sello', models.CharField(max_length=200)),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('componente', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api_app.componente')),
                ('computadora', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api_app.computadora')),
            ],
            options={
                'db_table': 'api_movimiento_componente',
            },
        ),
        migrations.CreateModel(
            name='Movimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=200)),
                ('estado', models.CharField(max_length=200)),
                ('serie', models.CharField(max_length=200)),
                ('responsable', models.CharField(max_length=200)),
                ('ubicacion', models.CharField(max_length=200)),
                ('sello_inv', models.CharField(max_length=200)),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('medio', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='api_app.medio')),
            ],
            options={
                'db_table': 'api_movimiento',
            },
        ),
    ]
