# Generated by Django 4.2.1 on 2023-08-02 04:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0040_movimientocomponente_movimiento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipomunicipio',
            name='provincia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_app.tipoprovincia'),
        ),
    ]
