# Generated by Django 4.2.1 on 2023-08-02 04:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0041_alter_tipomunicipio_provincia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipodepartamento',
            name='division',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_app.tipodivision'),
        ),
        migrations.AlterField(
            model_name='tipodivision',
            name='provincia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_app.tipoprovincia'),
        ),
        migrations.AlterField(
            model_name='tipounidad',
            name='division',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_app.tipodivision'),
        ),
        migrations.AlterField(
            model_name='tipounidad',
            name='municipio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_app.tipomunicipio'),
        ),
    ]
