# Generated by Django 4.2.1 on 2023-08-02 04:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0042_alter_tipodepartamento_division_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipopiso',
            name='unidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_app.tipounidad'),
        ),
    ]
